### PR TITLE
Allow dev to be set via config

### PR DESCRIPTION
**Pull request by LunarTwilight**
This way you don't have to edit the file to change it.

/cc @KockaAdmiralac

### CODE REVIEW

**Comment by KockaAdmiralac** [comment]
Thanks for the contribution!

Unfortunately, the change doesn't seem like it will perform well (every time the `User` class is initialized, which is currently happening on initial chat load and joining/leaving, it will load and parse the configuration file again which might be slow) and I'm trying to avoid duplication like this. Could you instead change the calls to `User.new` to accept a `Client` instance as the first parameter (it can be obtained via `@client` in plugins and `self` when in methods of the actual client or methods of modules that the client uses, such as the `Events` module) and change `Client#initialize` to accept a `Client` instance as the first parameter and set it as an instance variable (like `@client = client`) and then read from the `@client.config` variable when accessing the dev configuration?

Also, I'm not completely sure what's the reason behind the change: are you trying to restrict me access to bots that have a different dev configuration or just letting the bot recognize another person as its developer alongside me? The former seems like it will make maintenance harder for me and a more correct way to do the latter is:

```ruby
when :dev
  @name.eql?('KockaAdmiralac') or (!@client.config['dev'].nil? and @name.eql?(@client.config['dev']))
```

**Comment by LunarTwilight** [comment]
Ah, ok, I've updated the code to do that instead.

Yeah, the idea was to add another dev, so you don't have to edit the code to add a dev, you can just edit the config.

Also, I'm kinda curious as to what maintenance would need the bot thinking you're the dev, since the only use in the codebase is [here](https://github.com/KockaAdmiralac/chatbot-rb/blob/8084a6a0d122452e49469099c770c2bf6af62a93/plugin.rb#L71).

**Comment by KockaAdmiralac** [comment]
Dev privileges are the highest privileges in chatbot-rb, so they can execute everything other groups (chatmod, sysop, staff) can execute with the addition of the error log (since that only makes sense for a dev to see). What I meant is that if you restrict me dev access to bots that configured their dev differently I won't be able to debug issues with commands on these bots due to not having any permissions (which is what the previous code would do: dev permissions would only be granted to the configured dev OR to me if no dev is configured).

Did you test the changes to ensure the following:
- the chatbot boots up more or less correctly
- user joining doesn't cause any errors
- the chatbot responds to `!ignore` and `!unignore` commands the right way (by starting or stopping to ignore commands of a certain user)
- when a dev is configured it responds to all commands by that user regardless of their permissions
- regular permissions checks still work?

Also, could you update the documentation comment above `User#is?`? I realized it still says that the method checks whether the user is Sactage...

**Comment by LunarTwilight** [comment]
Ah.

I tested all of that and it seems to all be working fine, and no errors in chat or the logs.

And updated the comments. (I think `Instance` is the right thing to use there?)

**Comment by KockaAdmiralac** [comment]
The right thing to use there would be `Client`, since it's an instance of a `Client` object being passed as the first parameter. Otherwise, it looks good to me!

**Comment by LunarTwilight** [comment]
Ok, I changed `Instance` to `Client` 👍

**Comment by KockaAdmiralac** [comment]
Thanks again!

**Pull request merged**
