### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by LunarTwilight**
Wrap regex with parentheses to fix warnings.

/cc @KockaAdmiralac

### CODE REVIEW

**Comment by KockaAdmiralac** [comment]
- What warnings? The repository has no linter configured and default linter rules are possibly user-configurable through IDE options, so there's currently no "correct" way to write regex in this repository.
- The standard across this repository is no parentheses around regex and I see no good reason for changing that standard.
    - The reasoning behind [that rule in ESLint](https://eslint.org/docs/rules/wrap-regex) is that it "can end up looking like a division operator", which is rather unlikely for many use cases (as nobody is dividing regex) so I personally kept that rule disabled in all projects I maintain that use ESLint.

**Comment by LunarTwilight** [comment]
`ambiguous first argument; put parentheses or a space even after `/'
operator` is the warning I get, and I'm using the default linter that
comes with Ruby (`ruby -wc`) and I haven't configured any linting
other than enabling it in VSCode. Also I don't know why you're using
ESLint (which is a JS linter) in a Ruby project.

**Comment by KockaAdmiralac** [comment]
What the linter is complaining about can be fixed just as well by wrapping the whole method calls in parentheses instead of just the regex. Wrapping whole method calls in parentheses makes much more sense than wrapping only the regex, because the rule is there because of ambiguous method call borders, not ambiguous regex borders.
However, changing the code style around `match` makes the code style around `listen_to` inconsistent. IMO, the default linter is missing some way more obvious mistakes, so letting it dictate the code style of the whole project is not the best idea.

I never said I'm using ESLint in Ruby projects.

**Comment by LunarTwilight** [comment]
Ah. (also I saw you were talking about ESLint and thought you had though this was a JS project instead of a Ruby project lol)

**Pull request closed without merging**
